---
- name: CONFIGURE IPv6 EN LOOPBACK33
  hosts: cisco
  gather_facts: false
  connection: local

  tasks:
    - name: CREAR LOOPBACK33
      ios_config:
        lines:
          - interface Loopback33
          - description "LOOPBACK33 EXAMEN"
          - no shutdown

    - name: CONFIG IPv6 EN LOOPBACK33
      ios_config:
        parents: "interface Loopback33"
        lines:
          - ipv6 address 3001:ABCD:ABCD:1::1/128
          - ipv6 address FE80::1 link-local
